name: piggyzen
description: PiggyZen - Quản lý chi tiêu & tiết kiệm kỷ luật cực đoan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.jpg

# Tạo icon app từ avatar: dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/avatar.jpg"
  min_sdk_android: 21
  
